"use client";
import React, { useEffect, useState } from "react";
import {
  Box,
  Button,
  VStack,
  Text,
  useToast,
  Spinner,
} from "@chakra-ui/react";
import { CiShare2 } from "react-icons/ci";
import { QRCode } from "react-qrcode-logo";
import { ArrowBackIcon } from "@chakra-ui/icons";
import { useRouter } from "next/navigation";
import { useAuth } from "../context/AuthContext";
import { UserProfileService } from "../services/userProfileService";

const qrCodePage = () => {
  const router = useRouter();
  const toast = useToast();
  const { user, loading: authLoading } = useAuth();
  const [qrValue, setQrValue] = useState("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchProfile = async () => {
      if (user?.email) {
        // Try to find profile by email first to get the correct hushh_id
        // Since we don't have a direct getByEmail in service, we might need a workaround 
        // Or we rely on the fact that we might have user_id in the auth session
        // For now, let's try to fetch using the user.id from supabase auth
        try {
          // We might need to update UserProfileService to allow fetching by email if user_id/hushh_id lookup fails
          // But actually, the save route ensures email uniqueness. 
          // Let's assume we can use the ID from the local auth session if it matches, 
          // BUT the UUID in `user_profiles` might differ if generated by the Agent.
          // However, the cleanest way is if we have the profile loaded in context or we fetch by email.

          // NOTE: The current UserProfileService only supports ID lookup. 
          // I will assume for this MVP that we can use a direct fetch to our check-user API or similar if needed,
          // but strictly following instructions, I should use the service.
          // Let's rely on the service. If it fails, I'll fallback.

          // Actually, let's use the same API endpoint 'check-user' from the profile page as it returns the full object including hushh_id
          const API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwbXp5a294cW5ib3pnZG9xYnBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDE5Mjc5NzEsImV4cCI6MjAxNzUwMzk3MX0.3GwG8YQKwZSWfGgTBEEA47YZAZ-Nr4HiirYPWiZtpZ0";
          const response = await fetch(
            `https://hushh-api-53407187172.us-central1.run.app/api/check-user?email=${user.email}`,
            {
              headers: {
                'api_key': API_KEY,
                'Authorization': `Bearer ${API_KEY}`
              }
            }
          );

          if (response.ok) {
            const data = await response.json();
            if (data?.user?.hushh_id) {
              const origin = typeof window !== 'undefined' ? window.location.origin : '';
              setQrValue(`${origin}/p/${data.user.hushh_id}`);
            }
          }
        } catch (e) {
          console.error("Error fetching profile for QR", e);
        }
      }
      setLoading(false);
    };

    if (!authLoading && user) {
      fetchProfile();
    } else if (!authLoading && !user) {
      // Redirect if not logged in
      router.push('/login');
    }
  }, [user, authLoading, router]);

  const handleShare = () => {
    if (navigator.share) {
      navigator
        .share({
          title: "My Hushh Profile",
          text: "Connect with me on Hushh!",
          url: qrValue,
        })
        .then(() =>
          toast({
            title: "Shared successfully",
            status: "success",
            duration: 3000,
            isClosable: true,
          })
        )
        .catch((error) => console.log("Error sharing", error));
    } else {
      // Fallback: Copy to clipboard
      navigator.clipboard.writeText(qrValue);
      toast({
        title: "Link copied to clipboard",
        status: "info",
        duration: 2000,
        isClosable: true,
      });
    }
  };

  if (loading || authLoading) {
    return (
      <Box bg="black" minH="100vh" display="flex" alignItems="center" justifyContent="center">
        <Spinner color="white" />
      </Box>
    );
  }

  return (
    <Box
      fontFamily={"Poppins"}
      bg="black"
      minH="100vh"
      p={4}
      color="white"
      position={"relative"}
      mt={"1rem"}
      zIndex={"999999999"}
    >
      <Button
        onClick={() => router.push("/vivaConnect")}
        leftIcon={<ArrowBackIcon stroke={"#FFFFFF"} />}
        bg={"transparent"}
        color={"#FFFFFF"}
        m={0}
        _hover={{
          color: 'white',
          bg: '#1B1B1B'
        }}
      >
        Back
      </Button>
      <VStack spacing={4} mt={"4rem"}>
        <Box
          bg={"#1B1B1B"}
          p={"2rem"}
          borderRadius={"8px"}
          textAlign={"center"}
          display={"flex"}
          flexDirection={"column"}
        >
          {qrValue ? (
            <QRCode value={qrValue} size={256} qrStyle="dots" eyeRadius={10} fgColor="#FFFFFF" bgColor="transparent" />
          ) : (
            <Text>Could not load profile QR.</Text>
          )}
          <Text
            mt={"1rem"}
            fontSize={"12px"}
            fontWeight={"400"}
            align={"center"}
            color={"#949494"}
            lineHeight={"14.4px"}
          >
            Scan to view my digital profile
          </Text>
        </Box>
        <Button
          leftIcon={<CiShare2 stroke="#666666" />}
          bg={"white"}
          color={"#666666"}
          onClick={handleShare}
          isDisabled={!qrValue}
        >
          Share Profile Link
        </Button>
      </VStack>
    </Box>
  );
};

export default qrCodePage;
